### ISSUE TITLE
deleteStory not working

### ISSUE THREAD

**Issue by oneminusone** [mgp25/Snap-API#182]
`deleteStory` gives a `404 NOT_FOUND` error. I suppose the endpoint should be `/bq/delete_story` instead of `/delete_story`, but then there's a `400 BAD_REQUEST` error.

**Comment by mgp25** [comment]
@oneminusone I updated the endpoint, i'll test the request and response in a while and if its not working i'll update it

Thanks for noticing.

**Comment by mgp25** [comment]
@oneminusone it should work now, the request is the same as the client

Regards

**Comment by oneminusone** [comment]
It's still not working. The correct request includes the username and timestamp.

``` php
$result = parent::post(
    '/bq/delete_story',
    array(
        'story_id' => $storyId,
        'username' => $this->username,
        'timestamp' => $timestamp,
    ),
    array(
        $this->auth_token,
        $timestamp,
    ),
    $multipart = false,
    $debug = $this->debug
);
```
